[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "Simulation"
title = "bravo_arm_scripting_extension"
description = "first attempt at telling the bravo arm what to do in a scripting extension"
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}

[[python.module]]
name = "bravo_arm_scripting_extension_python"